const article_data = [{ "id": 1, "name": "Introducing TensorFlow Graphics", "description": "The last few years have seen a rise in novel differentiable graphics layers which can be inserted in neural network architectures. From spatial transformers to differentiable graphics renderers, these new layers leverage the knowledge acquired over years of computer vision and graphics research to build new and more efficient network architectures.", "time": "05/17/19 6:00PM" },
{ "id": 2, "name": "College Admissions Event", "description": "From 2006 to 2018, the acceptance rate among the top 50 US universities fell 36% and declined even more among the top 10 universities (60%). Stanford has an admissions rate of 4%; Harvard — 5%. The fact that your gene pool is no longer bound for UCLA but Pepperdine feels like you’ve failed as a parent.", "time": "05/19/19 9:00PM" },
{ "id": 3, "name": "Meet the World’s Most Bio-Tracked Man", "description": "Michael Snyder might be the most bio-tracked man in the world. He’s tested 14 of his “-omes,” such as the standard genome and microbiome as well as the less-well-known metabolome, transcriptome, proteome, immunome, and exposome.", "time": "05/21/19 10:00AM" },
{ "id": 4, "name": "Initial Skirmish in Broader Economic War", "description": "A yearlong trade war between the United States and China is proving to be an initial skirmish in an economic conflict that may persist for decades, as both countries battle for global dominance, stature and wealth. Progress toward a trade agreement nearly collapsed this past week, with both sides hardening their bargaining positions. And even if a trade deal is reached, it may do little to resolve tensions between the world’s two largest economies.", "time": "05/22/19 3:00PM" },
{ "id": 5, "name": "SWE GBM", "description": "A priest once admonished me at a wedding rehearsal that I wasn’t expressing emotion in a way that demonstrated I understood what love is while reading the couple’s selected psalm. “Perhaps you don’t know what it feels like because you don’t have love in your own life,” he continued to reprimand me, to my great humiliation, as a room full of silent people sat awkwardly. Even the flower girls and ring bearer who had been chasing each other through the pews sensed the vibe in the room change and suddenly stopped giggling.", "time": "05/22/19 3:00PM" },
{ "id": 6, "name": "Salsa Night", "description": "As Secretary of State Mike Pompeo appeared to be sounding the drums of war against Iran Thursday, and U.S. warships were steaming toward the region, a reporter asked President Donald Trump if there is a risk of military confrontation.", "time": "05/22/19 3:00PM" },
{ "id": 7, "name": "Game of Thrones Finale", "description": "For the 319 baby girls born and named Lyanna last year, “Game of Thrones” will never end. More parents are bestowing “Game of Thrones” character names on their children than ever, according to Social Security Administration data published Friday. Excluding the Jons and Jaimes, more than 4,500 children were given such names in 2018, up from the 3,800-plus in 2017 and the more than 3,200 in 2016.", "time": "05/22/19 3:00PM" },
{ "id": 8, "name": "Sen. Chris Murphy talk", "description": "Sen. Chris Murphy, a Democrat on the Senate Foreign Relations Committee, called Friday for a probe into Rudy Giuliani's efforts to influence investigations in Ukraine he anticipates as possibly beneficial to President Donald Trump, citing \"the implications of this for United States foreign policy.\"", "time": "05/22/19 3:00PM" }]

export default article_data;